
version: '3.8'

services:
  contacorrenteapi:
    build:
      context: ./src/ContaCorrenteAPI
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - shared-data:/app/Data

  transferenciaapi:
    build:
      context: ./src/TransferenciaAPI
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__ContaCorrente=http://contacorrenteapi
    volumes:
      - shared-data:/app/Data

volumes:
  shared-data: